name: PHPStan

on:
  pull_request:
  push:
    branches:
      - main
      - security/**
      - feature/**
      - homolog/**

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Analyse
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G
